import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';

export class JestFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'jest' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        groupToPath.set(key, `tests/${pathMeta.resource}/${test.request.method.toLowerCase()}-${pathMeta.leaf}.test.js`);
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const testBlocks = cases
        .map((testCase) => {
          const requestBody = JSON.stringify(testCase.request.body ?? null, null, 2);
          const requestQuery = JSON.stringify(testCase.request.query ?? {}, null, 2);
          const requestHeaders = JSON.stringify(testCase.request.headers ?? {}, null, 2);
          const contains = testCase.expected.contains?.length
            ? testCase.expected.contains.map((value) => `  expect(text).toContain(${JSON.stringify(value)});`).join('\n')
            : '  // No content assertions provided';

          return `test(${JSON.stringify(testCase.title)}, async () => {
  const query = new URLSearchParams(
    Object.entries(${requestQuery}).reduce((acc, [key, value]) => {
      if (value !== undefined && value !== null) {
        acc[key] = String(value);
      }
      return acc;
    }, {})
  ).toString();

  const response = await fetch(\`${'${BASE_URL}'}${testCase.request.path}${'${query ? `?${query}` : ""}'}\`, {
    method: ${JSON.stringify(testCase.request.method)},
    headers: {
      'Content-Type': 'application/json',
      ...${requestHeaders}
    },
    body: ${requestBody} !== null ? JSON.stringify(${requestBody}) : undefined
  });

  expect(response.status).toBe(${testCase.expected.status});
  const text = await response.text();
${contains}
});`;
        })
        .join('\n\n');

      return {
        path: groupToPath.get(groupKey) ?? `tests/${groupKey}.test.js`,
        content: `/**
 * Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}
 */
const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

${testBlocks}
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    return {
      path: 'README.md',
      content: `# APItiser Generated Jest Tests

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}

## Run

\`\`\`bash
npm install
API_BASE_URL=http://localhost:3000 npx jest tests
\`\`\`
`
    };
  }

  renderSupportFiles(): GeneratedFile[] {
    return [
      {
        path: 'jest.config.cjs',
        content: `module.exports = {\n  testMatch: ['**/tests/**/*.test.js'],\n  testTimeout: 30000\n};\n`
      },
      {
        path: 'package.json',
        content: `{\n  \"name\": \"apitiser-generated-tests\",\n  \"private\": true,\n  \"scripts\": {\n    \"test\": \"jest tests\"\n  },\n  \"devDependencies\": {\n    \"jest\": \"^29.7.0\"\n  }\n}\n`
      }
    ];
  }
}
