import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';
import { renderStatusAssertionJs } from '../statusExpectation';
import { jsTemplatePath, jsHeaderValueExpr, identityHeaders } from './runtimeTokens';
import { jsRuntimeHelpers, renderBodyAssertionsJs } from './assertions';

const headerValueExpr = (value: string): string => jsHeaderValueExpr(value);

const toHeadersObject = (headers: Record<string, string>): string => {
  const entries = Object.entries(headers);
  if (!entries.length) {
    return '{}';
  }
  return `{
      ${entries.map(([key, value]) => `${JSON.stringify(key)}: ${headerValueExpr(value)}`).join(',\n      ')}
    }`;
};

const PLAYWRIGHT_METHODS: Record<string, string> = {
  get: 'get',
  post: 'post',
  put: 'put',
  patch: 'patch',
  delete: 'delete',
  head: 'head'
};

export class PlaywrightFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'playwright' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        groupToPath.set(key, `tests/${pathMeta.resource}/${test.request.method.toLowerCase()}-${pathMeta.leaf}.spec.ts`);
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const blocks = cases
        .map((testCase) => {
          const method = testCase.request.method.toLowerCase();
          const requestMethod = PLAYWRIGHT_METHODS[method] ?? 'fetch';
          const effectiveHeaders = identityHeaders(testCase);
          const headers = toHeadersObject(effectiveHeaders);
          const hasHeaders = Object.keys(effectiveHeaders).length > 0;
          const hasQuery = Object.keys(testCase.request.query ?? {}).length > 0;
          const hasBody = testCase.request.body !== undefined && testCase.request.body !== null;

          const optionLines: string[] = [];
          if (hasHeaders) {
            optionLines.push(`    headers: ${headers}`);
          }
          if (hasQuery) {
            optionLines.push(`    params: ${JSON.stringify(testCase.request.query, null, 2).replace(/\n/g, '\n    ')}`);
          }
          if (hasBody) {
            optionLines.push(`    data: ${JSON.stringify(testCase.request.body, null, 2).replace(/\n/g, '\n    ')}`);
          }
          const optionsArg = optionLines.length ? `, {\n${optionLines.join(',\n')}\n  }` : '';

          const containsAsserts = (testCase.expected.contains ?? [])
            .map((value) => `  expect(text).toContain(${JSON.stringify(value)});`)
            .join('\n');
          const ctAssert = testCase.expected.contentType
            ? `  expect(response.headers()['content-type'] || '').toContain(${JSON.stringify(testCase.expected.contentType)});`
            : '';
          const headerAsserts = Object.entries(testCase.expected.responseHeaders ?? {})
            .map(([k, v]) => `  expect(response.headers()[${JSON.stringify(k.toLowerCase())}]).toBe(${JSON.stringify(v)});`)
            .join('\n');
          const schemaChecks = testCase.expected.jsonSchema
            ? `  assertSchemaShape(${JSON.stringify(testCase.expected.jsonSchema)}, body, 'response');`
            : '';
          const paginationCheck = testCase.expected.pagination ? `  expect(isPaginatedShape(body)).toBe(true);` : '';
          const bodyAssertions = renderBodyAssertionsJs(testCase, 'body', '  ', 'jest');
          const idempotencyCheck = testCase.expected.idempotent
            ? `  const repeat = await request.${requestMethod}(\`${'${BASE_URL}'}${jsTemplatePath(testCase.request.path)}\`${optionsArg});\n  assertIdempotent({ status: response.status(), json: body }, { status: repeat.status(), json: safeJsonParse(await repeat.text()) });`
            : '';

          return `test(${JSON.stringify(testCase.title)}, async ({ request }) => {
  // ${testCase.category} — identity: ${testCase.request.identity ?? 'primary'} — trust: ${testCase.trustLabel ?? 'heuristic'} (${testCase.trustScore ?? 0})
  const response = await request.${requestMethod}(\`${'${BASE_URL}'}${jsTemplatePath(testCase.request.path)}\`${optionsArg});
${renderStatusAssertionJs(testCase, 'response.status()', '  ')}
  const text = await response.text();
  const body = safeJsonParse(text);
${ctAssert}
${headerAsserts}
${containsAsserts}
${schemaChecks}
${bodyAssertions}
${paginationCheck}
${idempotencyCheck}
});`;
        })
        .join('\n\n');

      return {
        path: groupToPath.get(groupKey) ?? `tests/${groupKey}.spec.ts`,
        content: `/**
 * Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}
 * Set API_BASE_URL before running.
 * Replace placeholder auth values like Bearer {{API_TOKEN}} with real environment-backed credentials.
 */
import { test, expect } from '@playwright/test';

const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

const safeJsonParse = (text) => {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
};

${jsRuntimeHelpers('jest')}

test.describe(${JSON.stringify(groupKey)}, () => {
${blocks}
});
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    const validationLine = projectMeta.validationSummary
      ? `Validation: ${projectMeta.validationSummary.passed}/${projectMeta.validationSummary.attempted} passed`
      : 'Validation: not run';
    const readinessNotes = projectMeta.readinessNotes?.length
      ? `\n## Readiness Notes\n\n${projectMeta.readinessNotes.map((note) => `- ${note}`).join('\n')}\n`
      : '';
    return {
      path: 'README.md',
      content: `# APItiser Generated Playwright API Tests

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}
Readiness: ${projectMeta.readiness ?? 'review_required'}
${validationLine}

## Run

\`\`\`bash
npm install
export API_TOKEN=replace-me
API_BASE_URL=http://localhost:3000 npx playwright test
\`\`\`
${readinessNotes}`
    };
  }

  renderSupportFiles(_projectMeta?: ProjectMeta): GeneratedFile[] {
    return [
      {
        path: 'playwright.config.ts',
        content: `import { defineConfig } from '@playwright/test';\n\nexport default defineConfig({\n  testDir: './tests',\n  timeout: 30000\n});\n`
      },
      {
        path: 'package.json',
        content: `${JSON.stringify({
          name: 'apitiser-generated-tests',
          private: true,
          scripts: { test: 'playwright test' },
          devDependencies: { '@playwright/test': '^1.48.0' }
        }, null, 2)}\n`
      }
    ];
  }
}
