import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';

const toPyObject = (value: unknown): string => {
  return JSON.stringify(value ?? null, null, 2)
    .replace(/\btrue\b/g, 'True')
    .replace(/\bfalse\b/g, 'False')
    .replace(/\bnull\b/g, 'None');
};

export class PytestFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'pytest' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        groupToPath.set(key, `tests/${pathMeta.resource}/test_${test.request.method.toLowerCase()}_${pathMeta.leaf}.py`);
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const fnBlocks = cases
        .map((testCase, index) => {
          const fnName = `test_${groupKey}_${index + 1}`;
          const contains = testCase.expected.contains?.length
            ? testCase.expected.contains.map((value) => `    assert ${JSON.stringify(value)} in response.text`).join('\n')
            : '    # No content assertions provided';

          return `def ${fnName}():
    response = requests.request(
        method=${JSON.stringify(testCase.request.method)},
        url=f"{BASE_URL}${testCase.request.path}",
        headers=${toPyObject(testCase.request.headers ?? {})},
        params=${toPyObject(testCase.request.query ?? {})},
        json=${toPyObject(testCase.request.body ?? null)}
    )
    assert response.status_code == ${testCase.expected.status}
${contains}
`;
        })
        .join('\n');

      return {
        path: groupToPath.get(groupKey) ?? `tests/test_${groupKey}.py`,
        content: `"""Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}"""

import os
import requests

BASE_URL = os.getenv('API_BASE_URL', 'http://localhost:3000')

${fnBlocks}
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    return {
      path: 'README.md',
      content: `# APItiser Generated Pytest Suite

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}

## Run

\`\`\`bash
pip install requests pytest
API_BASE_URL=http://localhost:3000 pytest tests
\`\`\`
`
    };
  }

  renderSupportFiles(): GeneratedFile[] {
    return [
      {
        path: 'requirements.txt',
        content: `pytest>=8.0.0\nrequests>=2.32.0\n`
      },
      {
        path: 'pytest.ini',
        content: `[pytest]\ntestpaths = tests\n`
      }
    ];
  }
}
