import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';

const javaString = (value: string): string => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;

const headerValueExpr = (value: string): string => {
  if (value === 'Bearer {{API_TOKEN}}') {
    return `"Bearer " + envOr("API_TOKEN", "replace-me")`;
  }
  if (value === '{{API_KEY}}') {
    return `envOr("API_KEY", "replace-me")`;
  }
  if (value === '{{CSRF_TOKEN}}') {
    return `envOr("CSRF_TOKEN", "replace-me")`;
  }
  return javaString(value);
};

const javaClassName = (value: string): string => {
  const cleaned = value.replace(/[^a-zA-Z0-9]/g, ' ').trim();
  const camel = cleaned
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  const safe = camel || 'Api';
  return /^[0-9]/.test(safe) ? `T${safe}` : safe;
};

export class RestAssuredFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'restassured' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();
    const groupToClass = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        const className = `${javaClassName(`${pathMeta.resource}_${test.request.method}_${pathMeta.leaf}`)}Test`;
        groupToClass.set(key, className);
        groupToPath.set(key, `src/test/java/com/apitiser/generated/${className}.java`);
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const className = groupToClass.get(groupKey)!;
      const methods = cases
        .map((testCase, index) => {
          const methodName = `test_${index + 1}_${testCase.category}`;
          const headerLines = Object.entries(testCase.request.headers ?? {})
            .map(([k, v]) => `\t\t\t.header(${javaString(k)}, ${headerValueExpr(v)})`)
            .join('\n');
          const queryLines = Object.entries(testCase.request.query ?? {})
            .map(([k, v]) => `\t\t\t.queryParam(${javaString(k)}, ${javaString(String(v ?? ''))})`)
            .join('\n');
          const bodyLine =
            testCase.request.body !== undefined && testCase.request.body !== null
              ? `\t\t\t.body(${javaString(JSON.stringify(testCase.request.body))})`
              : '';
          const containsAsserts = (testCase.expected.contains ?? [])
            .map((s) => `\t\tassertTrue(body.contains(${javaString(s)}), "missing expected substring: ${s.replace(/"/g, '\\"')}");`)
            .join('\n');
          const ctAssert = testCase.expected.contentType
            ? `\t\tassertTrue(response.getContentType() != null && response.getContentType().contains(${javaString(testCase.expected.contentType)}), "content-type mismatch");`
            : '';
          const headerAsserts = Object.entries(testCase.expected.responseHeaders ?? {})
            .map(
              ([k, v]) =>
                `\t\tassertEquals(${javaString(v)}, response.getHeader(${javaString(k)}), "header ${k.replace(/"/g, '\\"')} mismatch");`
            )
            .join('\n');

          return `\t@Test
\t@DisplayName(${javaString(testCase.title)})
\tvoid ${methodName}() {
\t\t// Trust: ${testCase.trustLabel ?? 'heuristic'} (${testCase.trustScore ?? 0})
\t\tResponse response = given()
\t\t\t.baseUri(envOr("API_BASE_URL", "http://localhost:3000"))
\t\t\t.header("Content-Type", "application/json")
${headerLines}
${queryLines}
${bodyLine}
\t\t\t.when()
\t\t\t.request(${javaString(testCase.request.method)}, ${javaString(testCase.request.path)})
\t\t\t.then()
\t\t\t.extract().response();

\t\tassertEquals(${testCase.expected.status}, response.getStatusCode(), "status mismatch; body=" + response.getBody().asString());
\t\tString body = response.getBody().asString();
${ctAssert}
${headerAsserts}
${containsAsserts}
\t}`;
        })
        .join('\n\n');

      return {
        path: groupToPath.get(groupKey)!,
        content: `// Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}
package com.apitiser.generated;

import io.restassured.response.Response;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ${className} {
\tprivate static String envOr(String key, String def) {
\t\tString v = System.getenv(key);
\t\treturn (v == null || v.isEmpty()) ? def : v;
\t}

${methods}
}
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    const validationLine = projectMeta.validationSummary
      ? `Validation: ${projectMeta.validationSummary.passed}/${projectMeta.validationSummary.attempted} passed`
      : 'Validation: not run';
    const readinessNotes = projectMeta.readinessNotes?.length
      ? `\n## Readiness Notes\n\n${projectMeta.readinessNotes.map((n) => `- ${n}`).join('\n')}\n`
      : '';
    return {
      path: 'README.md',
      content: `# APItiser Generated REST Assured + JUnit5 Tests

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}
Readiness: ${projectMeta.readiness ?? 'review_required'}
${validationLine}

## Run

\`\`\`bash
export API_TOKEN=replace-me
API_BASE_URL=http://localhost:3000 mvn test
\`\`\`
${readinessNotes}`
    };
  }

  renderSupportFiles(projectMeta?: ProjectMeta): GeneratedFile[] {
    const artifactId = (projectMeta?.repo.repo ?? 'apitiser-generated-tests').replace(/[^a-zA-Z0-9_-]/g, '-');
    return [
      {
        path: 'pom.xml',
        content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
\t<modelVersion>4.0.0</modelVersion>
\t<groupId>com.apitiser</groupId>
\t<artifactId>${artifactId}</artifactId>
\t<version>1.0.0</version>
\t<properties>
\t\t<maven.compiler.source>17</maven.compiler.source>
\t\t<maven.compiler.target>17</maven.compiler.target>
\t</properties>
\t<dependencies>
\t\t<dependency>
\t\t\t<groupId>io.rest-assured</groupId>
\t\t\t<artifactId>rest-assured</artifactId>
\t\t\t<version>5.5.0</version>
\t\t\t<scope>test</scope>
\t\t</dependency>
\t\t<dependency>
\t\t\t<groupId>org.junit.jupiter</groupId>
\t\t\t<artifactId>junit-jupiter</artifactId>
\t\t\t<version>5.10.2</version>
\t\t\t<scope>test</scope>
\t\t</dependency>
\t</dependencies>
\t<build>
\t\t<plugins>
\t\t\t<plugin>
\t\t\t\t<groupId>org.apache.maven.plugins</groupId>
\t\t\t\t<artifactId>maven-surefire-plugin</artifactId>
\t\t\t\t<version>3.2.5</version>
\t\t\t</plugin>
\t\t</plugins>
\t</build>
</project>
`
      }
    ];
  }
}
