import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';
import { renderStatusAssertionJs } from '../statusExpectation';
import { jsPathExpr, jsHeaderValueExpr, identityHeaders } from './runtimeTokens';
import { jsRuntimeHelpers, renderBodyAssertionsJs } from './assertions';

const headerValueExpr = (value: string): string => jsHeaderValueExpr(value);

const renderHeadersChain = (headers: Record<string, string>): string =>
  Object.entries(headers)
    .map(([k, v]) => `      .set(${JSON.stringify(k)}, ${headerValueExpr(v)})`)
    .join('\n');

const renderQueryChain = (query: Record<string, unknown>): string => {
  const entries = Object.entries(query ?? {});
  if (!entries.length) return '';
  return `      .query(${JSON.stringify(query, null, 2).replace(/\n/g, '\n      ')})`;
};

export class SupertestFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'supertest' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        groupToPath.set(
          key,
          `tests/${pathMeta.resource}/${test.request.method.toLowerCase()}-${pathMeta.leaf}.test.js`
        );
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const blocks = cases
        .map((testCase) => {
          const method = testCase.request.method.toLowerCase();
          const headers = renderHeadersChain(identityHeaders(testCase));
          const query = renderQueryChain((testCase.request.query as Record<string, unknown>) ?? {});
          const body =
            testCase.request.body !== undefined && testCase.request.body !== null
              ? `      .send(${JSON.stringify(testCase.request.body, null, 2).replace(/\n/g, '\n      ')})`
              : '';
          const containsAsserts = (testCase.expected.contains ?? [])
            .map((s) => `    expect(response.text).toContain(${JSON.stringify(s)});`)
            .join('\n');
          const ctAssert = testCase.expected.contentType
            ? `    expect(response.headers['content-type'] || '').toContain(${JSON.stringify(testCase.expected.contentType)});`
            : '';
          const headerAsserts = Object.entries(testCase.expected.responseHeaders ?? {})
            .map(([k, v]) => `    expect(response.headers[${JSON.stringify(k.toLowerCase())}]).toBe(${JSON.stringify(v)});`)
            .join('\n');
          // Schema, pagination, and contract expectations were previously dropped by this
          // renderer (unlike jest/vitest/mocha/pytest), so supertest suites silently
          // under-asserted. response.body is already JSON-parsed by supertest.
          const schemaAsserts = testCase.expected.jsonSchema
            ? `    assertSchemaShape(${JSON.stringify(testCase.expected.jsonSchema, null, 2).replace(/\n/g, '\n    ')}, response.body, 'response');`
            : '';
          const paginationAssert = testCase.expected.pagination
            ? '    expect(isPaginatedShape(response.body)).toBe(true);'
            : '';
          const bodyAssertions = renderBodyAssertionsJs(testCase, 'response.body', '    ', 'jest');

          return `  test(${JSON.stringify(testCase.title)}, async () => {
    // ${testCase.category} — identity: ${testCase.request.identity ?? 'primary'} — trust: ${testCase.trustLabel ?? 'heuristic'} (${testCase.trustScore ?? 0})
    const response = await request(BASE_URL)
      .${method}(${jsPathExpr(testCase.request.path)})
      .set('Content-Type', 'application/json')
${headers}
${query}
${body};
${renderStatusAssertionJs(testCase, 'response.status', '    ')}
${ctAssert}
${headerAsserts}
${containsAsserts}
${schemaAsserts}
${paginationAssert}
${bodyAssertions}
  });`;
        })
        .join('\n\n');

      return {
        path: groupToPath.get(groupKey) ?? `tests/${groupKey}.test.js`,
        content: `/**
 * Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}
 * Set API_BASE_URL before running.
 */
const request = require('supertest');
const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

${jsRuntimeHelpers('jest')}

describe(${JSON.stringify(groupKey)}, () => {
${blocks}
});
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    const validationLine = projectMeta.validationSummary
      ? `Validation: ${projectMeta.validationSummary.passed}/${projectMeta.validationSummary.attempted} passed`
      : 'Validation: not run';
    const readinessNotes = projectMeta.readinessNotes?.length
      ? `\n## Readiness Notes\n\n${projectMeta.readinessNotes.map((n) => `- ${n}`).join('\n')}\n`
      : '';
    return {
      path: 'README.md',
      content: `# APItiser Generated Supertest Tests

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}
Readiness: ${projectMeta.readiness ?? 'review_required'}
${validationLine}

## Run

\`\`\`bash
npm install
export API_TOKEN=replace-me
API_BASE_URL=http://localhost:3000 npx jest tests
\`\`\`
${readinessNotes}`
    };
  }

  renderSupportFiles(_projectMeta?: ProjectMeta): GeneratedFile[] {
    return [
      {
        path: 'jest.config.cjs',
        content: `module.exports = {\n  testEnvironment: 'node',\n  testMatch: ['**/tests/**/*.test.js'],\n  testTimeout: 30000\n};\n`
      },
      {
        path: 'package.json',
        content: `${JSON.stringify({
          name: 'apitiser-generated-tests',
          private: true,
          scripts: { test: 'jest tests' },
          devDependencies: { jest: '^29.7.0', supertest: '^7.0.0' }
        }, null, 2)}\n`
      }
    ];
  }
}
