import type { GeneratedFile, GeneratedTestCase, ProjectMeta, TestFrameworkAdapter } from '@shared/types';
import { getResourcePath } from './pathing';
import { renderStatusAssertionJs } from '../statusExpectation';
import { jsPathExpr } from './runtimeTokens';

const headerValueExpr = (value: string): string =>
  value === 'Bearer {{API_TOKEN}}'
    ? "(process.env.API_TOKEN ? `Bearer ${process.env.API_TOKEN}` : 'Bearer replace-me')"
    : value === '{{API_KEY}}'
      ? "(process.env.API_KEY || 'replace-me')"
      : value === '{{CSRF_TOKEN}}'
        ? "(process.env.CSRF_TOKEN || 'replace-me')"
        : JSON.stringify(value);

const renderHeadersChain = (headers: Record<string, string>): string =>
  Object.entries(headers)
    .map(([k, v]) => `      .set(${JSON.stringify(k)}, ${headerValueExpr(v)})`)
    .join('\n');

const renderQueryChain = (query: Record<string, unknown>): string => {
  const entries = Object.entries(query ?? {});
  if (!entries.length) return '';
  return `      .query(${JSON.stringify(query, null, 2).replace(/\n/g, '\n      ')})`;
};

export class SupertestFrameworkAdapter implements TestFrameworkAdapter {
  readonly framework = 'supertest' as const;

  render(tests: GeneratedTestCase[], projectMeta: ProjectMeta): GeneratedFile[] {
    const grouped = new Map<string, GeneratedTestCase[]>();
    const groupToPath = new Map<string, string>();

    for (const test of tests) {
      const pathMeta = getResourcePath(test.request.path);
      const key = `${pathMeta.resource}_${test.request.method.toLowerCase()}_${pathMeta.leaf}`;
      if (!grouped.has(key)) {
        grouped.set(key, []);
        groupToPath.set(
          key,
          `tests/${pathMeta.resource}/${test.request.method.toLowerCase()}-${pathMeta.leaf}.test.js`
        );
      }
      grouped.get(key)?.push(test);
    }

    return [...grouped.entries()].map(([groupKey, cases]) => {
      const blocks = cases
        .map((testCase) => {
          const method = testCase.request.method.toLowerCase();
          const headers = renderHeadersChain(testCase.request.headers ?? {});
          const query = renderQueryChain((testCase.request.query as Record<string, unknown>) ?? {});
          const body =
            testCase.request.body !== undefined && testCase.request.body !== null
              ? `      .send(${JSON.stringify(testCase.request.body, null, 2).replace(/\n/g, '\n      ')})`
              : '';
          const containsAsserts = (testCase.expected.contains ?? [])
            .map((s) => `    expect(response.text).toContain(${JSON.stringify(s)});`)
            .join('\n');
          const ctAssert = testCase.expected.contentType
            ? `    expect(response.headers['content-type'] || '').toContain(${JSON.stringify(testCase.expected.contentType)});`
            : '';
          const headerAsserts = Object.entries(testCase.expected.responseHeaders ?? {})
            .map(([k, v]) => `    expect(response.headers[${JSON.stringify(k.toLowerCase())}]).toBe(${JSON.stringify(v)});`)
            .join('\n');
          // Schema, pagination, and contract expectations were previously dropped by this
          // renderer (unlike jest/vitest/mocha/pytest), so supertest suites silently
          // under-asserted. response.body is already JSON-parsed by supertest.
          const schemaAsserts = testCase.expected.jsonSchema
            ? `    assertSchemaShape(${JSON.stringify(testCase.expected.jsonSchema, null, 2).replace(/\n/g, '\n    ')}, response.body, 'response');`
            : '';
          const paginationAssert = testCase.expected.pagination
            ? '    expect(isPaginatedShape(response.body)).toBe(true);'
            : '';
          const contractComments = testCase.expected.contractChecks?.length
            ? testCase.expected.contractChecks
                .map((v) => `    // Contract expectation (verify manually): ${String(v).replace(/\s+/g, ' ').trim()}`)
                .join('\n')
            : '';

          return `  test(${JSON.stringify(testCase.title)}, async () => {
    // ${testCase.category} — trust: ${testCase.trustLabel ?? 'heuristic'} (${testCase.trustScore ?? 0})
    const response = await request(BASE_URL)
      .${method}(${jsPathExpr(testCase.request.path)})
      .set('Content-Type', 'application/json')
${headers}
${query}
${body};
${renderStatusAssertionJs(testCase, 'response.status', '    ')}
${ctAssert}
${headerAsserts}
${containsAsserts}
${schemaAsserts}
${paginationAssert}
${contractComments}
  });`;
        })
        .join('\n\n');

      return {
        path: groupToPath.get(groupKey) ?? `tests/${groupKey}.test.js`,
        content: `/**
 * Generated by APItiser for ${projectMeta.repo.owner}/${projectMeta.repo.repo}
 * Set API_BASE_URL before running.
 */
const request = require('supertest');
const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

const isPaginatedShape = (value) => Array.isArray(value)
  || (value && typeof value === 'object'
    && (['items', 'results', 'data'].some((key) => key in value) || Object.values(value).some((entry) => Array.isArray(entry))));

const assertSchemaShape = (schema, value, path = 'response') => {
  if (!schema) {
    return;
  }
  if (schema.type === 'array') {
    expect(Array.isArray(value)).toBe(true);
    if (schema.items && Array.isArray(value) && value.length > 0) {
      assertSchemaShape(schema.items, value[0], \`\${path}[0]\`);
    }
    return;
  }
  if (schema.type === 'object') {
    expect(value).not.toBeNull();
    expect(typeof value).toBe('object');
    for (const key of schema.required || []) {
      expect(value).toHaveProperty(key);
    }
    for (const [key, child] of Object.entries(schema.properties || {})) {
      if (value && Object.prototype.hasOwnProperty.call(value, key)) {
        assertSchemaShape(child, value[key], \`\${path}.\${key}\`);
      }
    }
    return;
  }
  if (schema.type === 'integer') {
    expect(Number.isInteger(value)).toBe(true);
    return;
  }
  if (schema.type === 'number') {
    expect(typeof value).toBe('number');
    return;
  }
  if (schema.type === 'boolean') {
    expect(typeof value).toBe('boolean');
    return;
  }
  expect(typeof value).toBe(schema.type || 'string');
};

describe(${JSON.stringify(groupKey)}, () => {
${blocks}
});
`
      };
    });
  }

  renderReadme(projectMeta: ProjectMeta): GeneratedFile {
    const validationLine = projectMeta.validationSummary
      ? `Validation: ${projectMeta.validationSummary.passed}/${projectMeta.validationSummary.attempted} passed`
      : 'Validation: not run';
    const readinessNotes = projectMeta.readinessNotes?.length
      ? `\n## Readiness Notes\n\n${projectMeta.readinessNotes.map((n) => `- ${n}`).join('\n')}\n`
      : '';
    return {
      path: 'README.md',
      content: `# APItiser Generated Supertest Tests

Generated at: ${projectMeta.generatedAt}
Repository: ${projectMeta.repo.owner}/${projectMeta.repo.repo}
Endpoints: ${projectMeta.endpointCount}
Readiness: ${projectMeta.readiness ?? 'review_required'}
${validationLine}

## Run

\`\`\`bash
npm install
export API_TOKEN=replace-me
API_BASE_URL=http://localhost:3000 npx jest tests
\`\`\`
${readinessNotes}`
    };
  }

  renderSupportFiles(_projectMeta?: ProjectMeta): GeneratedFile[] {
    return [
      {
        path: 'jest.config.cjs',
        content: `module.exports = {\n  testEnvironment: 'node',\n  testMatch: ['**/tests/**/*.test.js'],\n  testTimeout: 30000\n};\n`
      },
      {
        path: 'package.json',
        content: `${JSON.stringify({
          name: 'apitiser-generated-tests',
          private: true,
          scripts: { test: 'jest tests' },
          devDependencies: { jest: '^29.7.0', supertest: '^7.0.0' }
        }, null, 2)}\n`
      }
    ];
  }
}
