import type { ApiEndpoint, GeneratedTestCase, RepoRef } from '@shared/types';

interface PostmanItem {
  name: string;
  request: {
    method: string;
    header: { key: string; value: string }[];
    url: { raw: string; host: string[]; path: string[]; query?: { key: string; value: string }[] };
    body?: { mode: string; raw: string; options: { raw: { language: string } } };
  };
  event?: { listen: string; script: { exec: string[] } }[];
}

const buildPostmanItem = (test: GeneratedTestCase, endpoint: ApiEndpoint, baseUrl: string): PostmanItem => {
  const fullUrl = `${baseUrl}${test.request.path}`;
  const urlParts = test.request.path.replace(/^\//, '').split('/');

  const headers = Object.entries(test.request.headers ?? {}).map(([key, value]) => ({ key, value }));

  const queryItems = Object.entries(test.request.query ?? {}).map(([key, value]) => ({
    key,
    value: String(value)
  }));

  const item: PostmanItem = {
    name: `[${test.category}] ${test.title}`,
    request: {
      method: test.request.method,
      header: headers,
      url: {
        raw: queryItems.length ? `${fullUrl}?${queryItems.map((q) => `${q.key}=${q.value}`).join('&')}` : fullUrl,
        host: ['{{baseUrl}}'],
        path: urlParts,
        ...(queryItems.length ? { query: queryItems } : {})
      }
    }
  };

  if (test.request.body !== undefined && test.request.body !== null) {
    item.request.body = {
      mode: 'raw',
      raw: JSON.stringify(test.request.body, null, 2),
      options: { raw: { language: 'json' } }
    };
  }

  // Add test script for status assertion
  item.event = [{
    listen: 'test',
    script: {
      exec: [
        `pm.test("Status is ${test.expected.status}", function () {`,
        `  pm.response.to.have.status(${test.expected.status});`,
        `});`,
        ...(test.expected.contains ?? []).map((str) =>
          `pm.test("Response contains '${str}'", function () {\n  pm.expect(pm.response.text()).to.include("${str}");\n});`
        )
      ]
    }
  }];

  return item;
};

export const buildPostmanCollection = (
  repo: RepoRef,
  tests: GeneratedTestCase[],
  endpoints: ApiEndpoint[],
  baseUrl = 'http://localhost:3000'
): string => {
  const endpointsById = new Map(endpoints.map((ep) => [ep.id, ep]));
  const grouped = new Map<string, PostmanItem[]>();

  for (const test of tests) {
    const endpoint = endpointsById.get(test.endpointId);
    if (!endpoint) continue;

    const groupKey = `${endpoint.method} ${endpoint.path}`;
    const existing = grouped.get(groupKey) ?? [];
    existing.push(buildPostmanItem(test, endpoint, '{{baseUrl}}'));
    grouped.set(groupKey, existing);
  }

  const collection = {
    info: {
      name: `APItiser — ${repo.owner}/${repo.repo}`,
      description: `Generated by APItiser. Repo: ${repo.platform}:${repo.owner}/${repo.repo}`,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    variable: [
      { key: 'baseUrl', value: baseUrl, type: 'string' },
      { key: 'API_TOKEN', value: '', type: 'string' }
    ],
    item: [...grouped.entries()].map(([name, items]) => ({
      name,
      item: items
    }))
  };

  return JSON.stringify(collection, null, 2);
};
